---
- hosts: target_group
  become: true
  gather_facts: false
  become_user: root
  become_method: su
  become_exe: sudo su -
  tasks:
    - name: List packages installed on a selected date
      ansible.builtin.shell: hostnamectl | grep hostname; rpm -qa --last | grep "Mon Feb 12"
      register: command_output
      changed_when: false

    - name: Show output
      ansible.builtin.debug:
        var: command_output.stdout_lines
