---
- hosts: target_group
  become: true
  gather_facts: false
  become_user: root
  become_method: su
  become_exe: sudo su -
  tasks:
    - name: Copy the validation script to the server using generic paths
      ansible.builtin.copy:
        src: /path/to/local/validation_script.sh
        dest: /home/<user>/validation_script.sh
        mode: '0755'
